apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: thierno19/mongobackupgcs
            command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Authentification sur GCS..."
              gcloud auth activate-service-account --key-file=/etc/gcs-credentials/service-account.json
              echo "Lancement de mongodump..."
              mongodump --uri="mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}" --archive="/tmp/dump.gz" --gzip
              echo "Upload du dump sur GCS..."
              gsutil cp -r /tmp/dump.gz gs://mongodb-backup-dyma
            env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            - name: MONGODB_HOST
              value: mongodb-headless:27017
            - name: MONGODB_USER
              value: root
            volumeMounts:
            - name: gcs-credentials
              mountPath: /etc/gcs-credentials
          volumes:
          - name: gcs-credentials
            secret:
              secretName: gcs-credentials
          restartPolicy: OnFailure