name: Construire et pousser les images Docker sur Docker Hub et mettre à jour le répertoire infra pour déclencher Argo CD

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: front
            directory: ./frontend
            image: dymafr/chap19-front
          - name: api-node
            directory: ./node-api
            image: dymafr/chap19-node

    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v3

    - name: Obtenir le hash du dernier commit pour le tag des nouvelles images
      id: get_version
      run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Connexion à Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construire et pousser l'image ${{ matrix.name }}
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.directory }}
        file: ${{ matrix.directory }}/Dockerfile
        push: true
        tags: ${{ matrix.image }}:${{ env.VERSION }}
